### PR TITLE
Hopefully more robust cmd

### PR DESCRIPTION
**Pull request by ParadoxGuitarist**

### CODE REVIEW

**Comment by vwbusguy** [comment]
A few things:

* When I tested this out locally this way, it added `-e` to the ~/.Renviron and worked as expected without `-e`
* The docs suggest we should do it this way with a post hook call: https://z2jh.jupyter.org/en/stable/jupyterhub/customizing/user-environment.html#about-user-storage-and-adding-files-to-it
* Might be best to create this as /etc/skel/.Renviron and then cp it to /home/jovyan in CMD in addition to the helm so that this works for those running this generically in multi-user mode as well as single-user with a mount.

**Review by vwbusguy — CHANGES_REQUESTED** [review]
$ cat ~/.Renviron 
-e CMDSTAN=/opt/conda/bin/cmdstan
CMDSTANR_NO_VER_CHECK=TRUE

**Comment by ParadoxGuitarist** [comment]
Looks like the -e works as expected this way. 
```
[bmonroe@orden EEMB-174-container-image]$ podman run -it --rm  test /bin/bash 
(base) jovyan@b595bf3ccb67:~$ cat /tmp/.Renviron 
CMDSTAN=/opt/conda/bin/cmdstan
CMDSTANR_NO_VER_CHECK=TRUE
```

**Review by vwbusguy — COMMENTED** [review]
LGTM

**Pull request merged**
